import "./globals.css";

import { Urbanist } from "next/font/google";

import StoreProvider from "../components/providers/StoreProvider";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} bg-tertiary`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
