"use client";
import "./globals.css";

import { Urbanist } from "next/font/google";
import { Provider } from "react-redux";

import store from "../store/store";

import { checkAuth } from "../store/features/auth/checkAuthThunk";

const urbanist = Urbanist({ subsets: ["latin"] });

store.dispatch(checkAuth());

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} bg-tertiary`}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
